/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fangpai_cloudabull_serialportlibrary_serial_SerialPort */

#ifndef _Included_fangpai_cloudabull_serialportlibrary_serial_SerialPort
#define _Included_fangpai_cloudabull_serialportlibrary_serial_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fangpai_cloudabull_serialportlibrary_serial_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_fangpai_cloudabull_serialportlibrary_1serial_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     fangpai_cloudabull_serialportlibrary_serial_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fangpai_cloudabull_serialportlibrary_1serial_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
